### ISSUE TITLE
There are some race conditions while updating the node's information

### ISSUE THREAD

**Issue by jollaman999** [hcloud-classic/hcc-flute#1] opened 2021-06-28 02:39 UTC
There are some race conditions in ipmiCheck go routines.
The issue is exist in this file.
`lib/ipmi/ipmiCheck.go`

I think we should check if go routine is locked before re-run to prevent race conditions.

**Comment by hcloudclassic** [comment] 2021-06-28 02:40
@jollaman999 
Thank you for your advice.
The issue is fixed in https://github.com/hcloud-classic/hcc-flute/commit/9d9071f0277745bd8db30989cf7fc25d64aa7082.

**Closed as completed** 2021-06-28 02:40 UTC
Labels: bug, enhancement
